RES_STATUS = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
};

RES_ERROR_CODE = {
  MISSING_FIELD: "MISSING_FIELD",
  CANT_CREATE_RESOURCE: "CANT_CREATE_RESOURCE",
  SERVER_ERROR: "SERVER_ERROR",
  BAD_CREDENTIALS: "BAD_CREDENTIALS",
  EMAIL_EXIST: "EMAIL_EXIST",
};

module.exports = {
  RES_STATUS,
  RES_ERROR_CODE,
};
